import { Component, Inject, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatDialogRef, MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog';
import { LucideAngularModule } from 'lucide-angular';
import { ExportTemplateService } from '../../../core/services/export-template.service';
import { ExportTemplate } from '../../../core/models/export-template.model';
import { exportToExcel } from '../../../core/utils/xlsx-export.util';

@Component({
  selector: 'app-export-selector-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, LucideAngularModule],
  template: `
    <div class="p-6 bg-white rounded-2xl animate-in zoom-in duration-300">
      <div class="flex items-center justify-between mb-6">
        <div class="flex items-center space-x-3">
          <div class="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center">
            <lucide-icon name="file-spreadsheet" class="w-5 h-5"></lucide-icon>
          </div>
          <div>
            <h3 class="text-lg font-black text-slate-900 tracking-tight">Export to Excel</h3>
            <p class="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Select a template to generate the file</p>
          </div>
        </div>
        <button (click)="close()" class="p-2 text-slate-400 hover:text-slate-600 transition-colors">
          <lucide-icon name="x" class="w-5 h-5"></lucide-icon>
        </button>
      </div>

      <!-- Templates List -->
      <div class="space-y-3" *ngIf="availableTemplates().length > 0">
        <button *ngFor="let template of availableTemplates()" 
                (click)="export(template)"
                class="w-full text-left p-4 rounded-2xl border border-slate-100 hover:border-emerald-200 hover:bg-emerald-50/30 transition-all flex items-center justify-between group active:scale-[0.98]">
          <div class="flex items-center space-x-4">
            <div class="w-8 h-8 rounded-lg bg-white border border-slate-100 flex items-center justify-center text-slate-400 group-hover:text-emerald-500 group-hover:border-emerald-100 transition-colors shadow-sm">
              <lucide-icon name="layout" class="w-4 h-4"></lucide-icon>
            </div>
            <div class="flex flex-col">
              <span class="text-sm font-bold text-slate-700 underline-offset-4 decoration-2"> {{ template.name }} </span>
              <span class="text-[10px] text-slate-400 font-medium truncate max-w-[200px]"> {{ template.columns.length }} columns mapping </span>
            </div>
          </div>
          <lucide-icon name="chevron-right" class="w-4 h-4 text-slate-300 group-hover:text-emerald-500 group-hover:translate-x-1 transition-all"></lucide-icon>
        </button>
      </div>

      <!-- Empty State -->
      <div *ngIf="availableTemplates().length === 0" class="flex flex-col items-center justify-center py-10 px-6 bg-slate-50 rounded-2xl border-2 border-dashed border-slate-100 text-center">
        <div class="w-16 h-16 bg-white rounded-full flex items-center justify-center mb-4 shadow-sm text-slate-200">
          <lucide-icon name="alert-circle" class="w-8 h-8"></lucide-icon>
        </div>
        <h4 class="text-sm font-bold text-slate-900">No Templates Found</h4>
        <p class="text-[11px] text-slate-500 mt-2 max-w-[200px]">You haven't created any templates for this list yet.</p>
        <button (click)="goToTemplates()" class="mt-6 text-[11px] font-black text-blue-600 uppercase tracking-widest hover:underline active:scale-95 transition-all">
          Go to Configuration
        </button>
      </div>

      <div class="mt-8 pt-4 border-t border-slate-50 text-center">
        <p class="text-[9px] font-bold text-slate-300 uppercase tracking-[0.2em]">Generated by OrderFlow Export System</p>
      </div>
    </div>
  `
})
export class ExportSelectorDialogComponent {
  private templateService = inject(ExportTemplateService);
  private dialogRef = inject(MatDialogRef<ExportSelectorDialogComponent>);
  
  constructor(@Inject(MAT_DIALOG_DATA) public data: { sourceKey: string; dataset: any[] }) {}

  availableTemplates() {
    return this.templateService.getTemplatesBySource(this.data.sourceKey);
  }

  close() {
    this.dialogRef.close();
  }

  export(template: ExportTemplate) {
    exportToExcel(template, this.data.dataset);
    this.dialogRef.close(true);
  }

  goToTemplates() {
    this.dialogRef.close('GOTO');
  }
}
